version: '3.9'
services:
    redis:
        image: redis:7-alpine
        container_name: torchlife_redis
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data

volumes:
    redis_data:

        # postgres:
        #     image: postgres:16
        #     container_name: postgres_db
        #     environment:
        #         POSTGRES_USER: postgres
        #         POSTGRES_PASSWORD: password
        #         POSTGRES_DB: torchlife_main_db
        #     ports:
        #         - '5432:5432'
        #     volumes:
        #         - postgres_data:/var/lib/postgresql/data
#     app:
#         build: .
#         container_name: nest-app
#         command: npm run start:dev
#         ports:
#             - '3000:3000'
#         environment:
#             REDIS_HOST: redis
#             REDIS_PORT: 6379
#         depends_on:
#             - redis

# volumes:
#     redis_data:
